### ISSUE TITLE
`describepids()` not working on my cluster

### ISSUE THREAD

**Issue by klkeys** [pearcemc/ClusterUtils.jl#1]
On my machine, `describepids` does not work as in the example.

```
using ClusterManagers; addprocs(LocalAffinityManager(np=2,mode=COMPACT,affinities=Int[]));
@everywhere using ClusterUtils
# WARNING: replacing module ClusterUtils
# WARNING: Method definition display(Base.SharedArray) in module ClusterUtils at /share/apps/julia-0.4.0/share/julia/site/v0.4/ClusterUtils/src/ClusterUtils.jl:166 overwritten in module ClusterUtils at /share/apps/julia-0.4.0/share/julia/site/v0.4/ClusterUtils/src/ClusterUtils.jl:166.
# WARNING: replacing module ClusterUtils
# WARNING: Method definition display(Base.SharedArray) in module ClusterUtils at /share/apps/julia-0.4.0/share/julia/site/v0.4/ClusterUtils/src/ClusterUtils.jl:166 overwritten in module ClusterUtils at /share/apps/julia-0.4.0/share/julia/site/v0.4/ClusterUtils/src/ClusterUtils.jl:166.
describepids()
# ERROR: MethodError: `remotecall_fetch` has no method matching remotecall_fetch(::Function, ::Int64, ::Cmd)
# Closest candidates are:
#  remotecall_fetch(::LocalProcess, ::Any, ::Any...)
#  remotecall_fetch(::Base.Worker, ::Any, ::Any...)
#  remotecall_fetch(::Integer, ::Any, ::Any...)
#  in makefiltermaster at /share/apps/julia-0.4.0/share/julia/site/v0.4/ClusterUtils/src/ClusterUtils.jl:66
#  in describepids at /share/apps/julia-0.4.0/share/julia/site/v0.4/ClusterUtils/src/ClusterUtils.jl:115
```

**Comment by pearcemc** [comment]
Thanks for noting this. I haven't tested on v0.4 :( Looks like there's a difference in the behaviour of `remotecall_fetch'.

**Comment by pearcemc** [comment]
Hi, I committed something I think should help the immediate problem. I was retrieving hostname using sys commands, but it looks like `gethostname()` does the trick instead and I understand from the other thread that that works on your 0.4.

**Comment by klkeys** [comment]
Commit 200ce66 still doesn't fix the problem. Something about the `reap` function?

```
using ClusterManagers
addprocs(LocalAffinityManager(np=2,mode=COMPACT,affinities=Int[]));
import ClusterUtils
ClusterUtils.describepids()
# ERROR: MethodError: `remotecall_fetch` has no method matching remotecall_fetch(::Function, ::Int64, ::Expr)
# Closest candidates are:
#   remotecall_fetch(::LocalProcess, ::Any, ::Any...)
#   remotecall_fetch(::Base.Worker, ::Any, ::Any...)
#   remotecall_fetch(::Integer, ::Any, ::Any...)
# in anonymous at task.jl:447
# in sync_end at ./task.jl:413
# [inlined code] from task.jl:422
# in reap at /share/apps/julia-0.4.0/share/julia/site/v0.4/ClusterUtils/src/ClusterUtils.jl:193
# in makefiltermaster at /share/apps/julia-0.4.0/share/julia/site/v0.4/ClusterUtils/src/ClusterUtils.jl:59
# in describepids at /share/apps/julia-0.4.0/share/julia/site/v0.4/ClusterUtils/src/ClusterUtils.jl:10
```

**Comment by pearcemc** [comment]
Cheers. Looks like the remotecall function was changed in v0.5. That must be the root of the earlier problem as well. (https://github.com/JuliaLang/julia/blob/master/NEWS.md).

**Comment by pearcemc** [comment]
Hi, having looked into it `using Compat` solves the issues by switching round the order of arguments to `remotecall` operations which was at the root of the problem.  Might be a bit late for you, apologies, but I'll close off.

``` julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.5 (2016-03-18 00:58 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-unknown-linux-gnu

julia> using ClusterUtils

julia> using ClusterManagers

julia> remotes = addprocs(SlurmManager(12), partition="mrc-bsu-tesla", account="MRC-BSU-SL2-GPU", t="24:00:00", nodes=1);
srun: job 2365784 queued and waiting for resources
srun: job 2365784 has been allocated resources
connecting to worker 12 out of 12
julia> using Compat

julia> #sow([2,3,4], :A, :(myid()*ones(10,10)))

julia> describepids()
Dict{Int64,Array{Int64,1}} with 1 entry:
  2 => [2,3,4,5,6,7,8,9,10,11,12,13]

julia> sow([2,3,4], :A, :(myid()*ones(10,10)))
Dict{Int64,RemoteRef{T<:AbstractChannel}} with 3 entries:
  4 => RemoteRef{Channel{Any}}(4,1,54)
  2 => RemoteRef{Channel{Any}}(2,1,50)
  3 => RemoteRef{Channel{Any}}(3,1,52)

julia> reap([2,3,4], :(sum(A)))
Dict{Int64,Any} with 3 entries:
  4 => 400.0
  2 => 200.0
  3 => 300.0
```
